name: Generate Badges

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'badges/*'


jobs:
  badges:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest pytest-cov anybadge flake8
          pip install -r requirements.txt

      - name: Run pylint
        run: pylint app.py --exit-zero --output-format=json > pylint-report.json

      - name: Run pytest with coverage
        run: pytest --cov=app --cov-report=xml --cov-report=term

      - name: Run flake8 for PEP8
        run: flake8 app.py --count --statistics --exit-zero > flake8-report.txt

      - name: Create badges
        run: |
          python badges/generate_badges.py > badge_values.txt
          export CODE_QUALITY=$(grep -oP 'Code Quality: \K\d+' badge_values.txt)
          export TEST_COVERAGE=$(grep -oP 'Test Coverage: \K\d+' badge_values.txt)
          export PEP8_COMPLIANCE=$(grep -oP 'PEP8 Compliance: \K\d+' badge_values.txt)

          echo "CODE_QUALITY=$CODE_QUALITY" >> $GITHUB_ENV
          echo "TEST_COVERAGE=$TEST_COVERAGE" >> $GITHUB_ENV
          echo "PEP8_COMPLIANCE=$PEP8_COMPLIANCE" >> $GITHUB_ENV

