name: Generate Badges

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'badges/*'


jobs:
  badges:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest pytest-cov anybadge flake8
          pip install -r requirements.txt

      - name: Run pylint
        run: pylint app.py --exit-zero --output-format=json > pylint-report.json

      - name: Run pytest with coverage
        run: pytest --cov=app --cov-report=xml --cov-report=term

      - name: Run flake8 for PEP8
        run: flake8 app.py --count --statistics --exit-zero > flake8-report.txt

      - name: Commit and push badge_values.json
        run: |
          python badges/generate_badges.py
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add badges/badge_values.json
          git commit -m "Update badge_values.json" || exit 0
          git push
